import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title> Hunting Blog </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.mainnav}>
        <ul>
          <li><a href="#"></a> Home </li>
          <li><a href="#"></a> About </li>
          <li><a href="#"></a> Blog </li>
          <li><a href="#"></a> Contact </li>
        </ul>
      </div>
      <main className={styles.main}>
        <div className={styles.center}>
          <h2> A Blog For Hunting Coders By a Hunting Coder  </h2>
        </div>
      
        <div className={styles.blog}>
          <h2> Popular Blog </h2>
            <div className={styles.blog_item}>
              <h3> How to learn Next js in 2022 </h3>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloribus eum reprehenderit aut rerum iste a neque officia qui dolores voluptatibus.</p>
            </div>
            <div className={styles.blog_item}>
              <h3> How to learn Next js in 2022 </h3>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloribus eum reprehenderit aut rerum iste a neque officia qui dolores voluptatibus.</p>
            </div>
            <div className={styles.blog_item}>
              <h3> How to learn Next js in 2022 </h3>
              <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Doloribus eum reprehenderit aut rerum iste a neque officia qui dolores voluptatibus.</p>
            </div>
        </div>
      </main>
    </>
  )
}
